
FRACTIES = {'Forum voor Democratie': {'Afkorting': 'FvD', 'Zetels': 5},
 'Volkspartij voor Vrijheid en Democratie': {'Afkorting': 'VVD','Zetels': 34},
 'DENK':{'Afkorting':  'DENK','Zetels': 3},
 'Groep Van Haga':{'Afkorting':  'Haga','Zetels': 2},
 'Fractie Den Haan': {'Afkorting': 'Den Haan','Zetels': 1},
 'Volt': {'Afkorting': 'Volt','Zetels': 2},
 'Partij van de Arbeid': {'Afkorting': 'PvdA','Zetels': 9},
 'BBB': {'Afkorting': 'BBB','Zetels': 4},
 'Democraten 66': {'Afkorting': 'D66','Zetels': 24},
 'Staatkundig Gereformeerde Partij': {'Afkorting': 'SGP','Zetels': 3},
 'Christen-Democratisch Appèl': {'Afkorting': 'CDA','Zetels': 14},
 'Socialistische Partij': {'Afkorting': 'SP','Zetels': 9},
 'Partij voor de Vrijheid': {'Afkorting': 'PVV','Zetels': 16},
 'Partij voor de Dieren': {'Afkorting': 'PvdD','Zetels': 6},
 'GroenLinks': {'Afkorting': 'GL','Zetels': 8},
 'Gündoğan': {'Afkorting': 'Gündoğan','Zetels': 1},
 'JA21': {'Afkorting': 'JA21','Zetels': 1},
 'Omtzigt': {'Afkorting': 'Omtzigt','Zetels': 1},
 'ChristenUnie': {'Afkorting': 'CU','Zetels': 5},
 'BIJ1': {'Afkorting': 'BIJ1', 'Zetels': 1},
 'Ephraim' : {'Afkorting': 'Ephraim','Zetels' : 1},
}